### PR TITLE
Mega board kicad dev

### PR DESCRIPTION
**Pull request by xcancerberox**
First version of the mega board on kicad.

There is some components that are not defined. This is going to be defined on an other PR with the full BOM.

### CODE REVIEW

**Comment by spiccinini** [comment]
Review

- Core 9558 module:
    - Pin 95 tiene que ir conectado a GND y no a 3V3
    - Cambiar 5V1 por 5V_1
- PCIe doughterboard (y circuito de alrededor)
    - PCIE0-37 esta conectado a tierra y no debería (al menos no esta en el circuito original)
- USB interface
    - USB_1_N y USB_1_P estan invertidos en el conector de USB_INT
- Watchdog
    - Agregar comentario  KICK_IN en GPIO2/WT_MOSI (mejora)
- RF control OK
- GPS header OK
- Expose IO  OK
- UART header OK
- Button OK
- LED interface OK
- Power
    - Los enables de 5V0, 5V1 y 5V2 en el circuito original no estan unidos? Hay uno que tiene un pullup y el resto "son el mismo net". Lo mismo con los enables de 3v3
    - POWER_EN_5V tiene que estar conectado a los 5V_{0,1,2}_ENABLE (esta conectado a 3v3_enable)
- Ethernet & PoE
    - Esta invertido el orden de los AT_TRX{0,1,2,3}_N/P  (AT_TRX0_N deberia ser AT_TRX4_N). Lo mismo con lo AM_TRX y con los BT y BM.

**Comment by xcancerberox** [comment]
> Review
> 
>     * Core 9558 module:
>       
>       * Pin 95 must be connected to GND (and not to 3V3)
Fix on d01ab478f5ba438a53f06724cf6a805792b525de
>       * Change the name of 5V1 por 5V_1 or if it is not posible change it to other name (because 5V1 reads like 5.1V)

Fix on 5383465d9552fef99bd209cce7c05eef22443e93

> 
>     * PCIe doughterboard
>       
>       * PCIE0-37 is connected to GND but it shouldn't (at least in the original circuit is not connected to GND)

Open discussion here: https://github.com/LibreRouterOrg/board/issues/37

> 
>     * USB interface
>       
>       * USB_1_N y USB_1_P are inverted at USB_INT connector
>

Fix on 89df6d81acfde865a0fa8b81c2a3799a4a3821d2
 
>     * Watchdog
>       
>       * Add comment  KICK_IN or WDG_KICK_IN at GPIO2/WT_MOSI (so it is easier to follow the circuit)
> 

I'm not sure what do you mean.

>     * RF control OK
> 
>     * GPS header OK
> 
>     * Expose IO  OK
> 
>     * UART header OK
> 
>     * Button OK
> 
>     * LED interface OK
> 
>     * Power
>       
>       * 5V0, 5V1 and 5V2 enables in the original circuit are joined in the same net. The same for 3v3 enables.
>       * POWER_EN_5V must be connected to 5V_{0,1,2}_ENABLE but it is connected to 3v3_enable

Both fix on 06f79c3877c7c8dee0f6f1c574e52fdb4cc397ba

> 
>     * Ethernet & PoE
>       
>       * The order of AT_TRX{0,1,2,3}_N/P  is inverted (eg: AT_TRX0_N should be  AT_TRX4_N). The same for AM_TRX and BT y BM.

I found that AT_TRX{0,1,2,3}_N is connected to TD+, and that's not ok. Same for the rest.
But I don't see what you are saying.

**Comment by spiccinini** [comment]
>>    * Ethernet & PoE  
>>      * The order of AT_TRX{0,1,2,3}_N/P  is inverted (eg: AT_TRX0_N should be  AT_TRX4_N). The same for AM_TRX and BT y BM.


> I found that AT_TRX{0,1,2,3}_N is connected to TD+, and that's not ok. Same for the rest.
> But I don't see what you are saying .
Yes I saw that TD+ where connected to N, and TD- to P, but in the original schematic is in this way right? Probably it works because the automatic detection of polarity of the switch/eth?

What I was trying to say is that in the original schematic S17_P4_TRX3_N is connected to pin 2. And that in the kicad schematic AT_TRX3_N is connected to pin 11.

**Comment by xcancerberox** [comment]
> > > * Ethernet & PoE
> > >   
> > >   * The order of AT_TRX{0,1,2,3}_N/P  is inverted (eg: AT_TRX0_N should be  AT_TRX4_N). The same for AM_TRX and BT y BM.
> 
> > I found that AT_TRX{0,1,2,3}_N is connected to TD+, and that's not ok. Same for the rest.
> > But I don't see what you are saying .
> > Yes I saw that TD+ where connected to N, and TD- to P, but in the original schematic is in this way right? Probably it works because the automatic detection of polarity of the switch/eth?
> 
> What I was trying to say is that in the original schematic S17_P4_TRX3_N is connected to pin 2. And that in the kicad schematic AT_TRX3_N is connected to pin 11.

Changed on de01fdac102446a1e82c295c973b9ac3375ec847

**Comment by xcancerberox** [comment]
WD and PCI20 Wake net change on 690515e4ffa0c53cdab0fa40c52006e847cd9986 for clarity

**Pull request merged**
